

spring:
  application:
    name:
      Front-Gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: middle-order
          uri: lb://middle-order
          predicates:
            - Path=/orders/**
        - id: middle-product
          uri: http://localhost:19093
          predicates:
            - Path=/products/**
            - Weight=group-product, 3
        - id: middle-product
          uri: http://localhost:19094
          predicates:
            - Path=/products/**
            - Weight=group-product, 7
        - id: middle-auth
          uri: lb://middle-auth
          predicates:
            - Path=/auth/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:19090/eureka/

service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

server:
  port: 19091
